### ISSUE TITLE
deviceCountry and deviceLocale dynamic?

### ISSUE THREAD

**Issue by delanick** [DeepakArora76/nativescript-dna-deviceinfo#1]
Hi @DeepakArora76 

Loving this plugin, thank you! I just want to know, does the deviceLocale and device Country change based on a user's location or are they fixed to where that device was distributed by a carrier? If I have a user that is based in country X and registers that way, but travels to country Y, will deviceCountry() pick that up? I need to display content based on where the user is at that point and not only based on their country of registration on the app. Please advise :)

Also, where is the device pulling the country and locale data from, network level?

**Comment by DeepakArora76** [comment]
Thank you for your kind words.

Device´s locale and country are based on users settings/configurations, and it won´t change even if there is a change in users´ home country.

Device timezone can be something which may come handy in your use case. 

You could also use **nativescript-geolocation** plugin to get _latitude_ and _longitude_ and feed them to [web API](http://maps.googleapis.com/maps/api/geocode/json?latlng=11.2742848,75.8013801) to get country.

**Comment by delanick** [comment]
@DeepakArora76 Always! :)

I think the Web API option will have to do, as I am in South Africa, got my device in South Africa from our largest carrier (part of Vodafone) and yet my country and locale on my device is listed as Great Britain. So I've got no idea how to fix that.

My app allows users to change countries, but I want to pre-populate the countries list based on where they sign up for the first time.

Will check Web API out - thanks a ton!
