### ISSUE TITLE
androidx error

### ISSUE THREAD

**Issue by dengyy-cq** [DeepakArora76/nativescript-dna-deviceinfo#2]
in deviceinfo.android.js
line 260
android.support.v4.content.ContextCompat

**Comment by shemekh** [comment]
I have checked it. When you change in node_modules\nativescript-dna-deviceinfo\deviceinfo.android.js: 
`android.support.v4.content.ContextCompat`
to
`androidx.core.content.ContextCompat`
It works as expected.
Without this change the error is:
`ERROR TypeError: Cannot read property 'ContextCompat' of undefined`

I will leave here also an url to the current mappings from old support library artifacts to androidx.
https://developer.android.com/jetpack/androidx/migrate/artifact-mappings

**Comment by DeepakArora76** [comment]
Hopefully fixed in 2.4.3 release.
