### ISSUE TITLE
DeviceInfo.isEmulator() returns false for some virtual devices

### ISSUE THREAD

**Issue by timbell** [DeepakArora76/nativescript-dna-deviceinfo#21]
`DeviceInfo.isEmulator()` erroneously returns `false` for some virtual devices. For example, with `Pixel 4 XL API 30` the following values are reported by `android.os.Build`:

FINGERPRINT: `'google/sdk_gphone_x86_arm/generic_x86_arm:11/RSR1.201013.001/6903271:userdebug/dev-keys'`
MODEL: `'sdk_gphone_x86_arm'`
MANUFACTURER: `'Google'`
BRAND: `'google'`
DEVICE: `'generic_x86_arm'`
PRODUCT: `'sdk_gphone_x86_arm'`

**Comment by DeepakArora76** [comment]
@timbell, thank you for reporting the issue. I will extend the check for an emulator with `generic_x86_arm`.  I will release an updated plugin sometime over the coming weekend.

The existing code:
 ```
 const Build = android.os.Build;
    return Build.FINGERPRINT.startsWith("generic") || Build.FINGERPRINT.startsWith("unknown")
      || Build.MODEL.includes("google_sdk") || Build.MODEL.includes("Emulator")
      || Build.MODEL.includes("Android SDK built for x86") || Build.MANUFACTURER.includes("Genymotion")
      || (Build.BRAND.startsWith("generic") && Build.DEVICE.startsWith("generic"))
      || "google_sdk" === Build.PRODUCT;
```

**Comment by DeepakArora76** [comment]
@timbell, please use the latest plugin version 3.7.3.

**Comment by timbell** [comment]
@DeepakArora76 many thanks - works great
