### ISSUE TITLE
Deprecated API usage

### ISSUE THREAD

**Issue by igorgiovannini** [DeepakArora76/nativescript-dna-deviceinfo#5]
Platform: **iOS**
Version: **latest**

`ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).`

Apple refuses by default every new application with references to UIWebView APIs.

In the _deviceinfo.ios.ts_ there is a reference to UIWebView (in order to grab the current useragent).
The old UIWebView **stringByEvaluatingJavaScriptFromString** method is no longer available as it is in the new WKWebView.

WKWebView has **evaluateJavaScript** method which the result is returned in a closure (completion handler): https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript

**Comment by SergioZhydecky** [comment]
The same issue

**Comment by DeepakArora76** [comment]
@igorgiovannini @SergioZhydecky Fixed in the latest release.
