### ISSUE TITLE
Error on build latest NS7

### ISSUE THREAD

**Issue by HakobiDev** [DeepakArora76/nativescript-dna-deviceinfo#9]
I had install the latest migrated at this plugin but unfortunetely, I encounter this error in build runtime

```
ERROR in ../node_modules/reduce-css-calc/dist/lib/convert.js
Module not found: Error: Can't resolve 'css-unit-converter' in 'C:\Users\Kronos\Desktop\KronosMobile\nativeRevise\kronos\node_modules\reduce-css-calc\dist\lib'
 @ ../node_modules/reduce-css-calc/dist/lib/convert.js 7:24-53
 @ ../node_modules/reduce-css-calc/dist/lib/reducer.js
```

**Comment by DeepakArora76** [comment]
@HakobiDev Thank you for testing and reporting an issue. 

It is strange to see an error that is not related to plug-in code. The plugin does not have any dependency on reduce-css-calc module. Here is the link to package.json file which shows dev-dependency the package has.

https://github.com/DeepakArora76/nativescript-dna-deviceinfo/blob/master/src/package.json#L88

I believe this is something related to your work. 

In any case, I will try to repro the problem by downloading the plug-in.

**Comment by DeepakArora76** [comment]
The link https://github.com/DeepakArora76/nativescript-dna-deviceinfo/blob/master/src/package-lock.json shows that there is something that ref reduce-css-calc. I will attempt to dig out more about it.
    
"reduce-css-calc": {
      "version": "2.1.8",
      "resolved": "https://registry.npmjs.org/reduce-css-calc/-/reduce-css-calc-2.1.8.tgz",
      "integrity": "sha512-8liAVezDmUcH+tdzoEGrhfbGcP7nOV4NkGE3a74+qqvE7nt9i4sKLGBuZNOnpI4WiGksiNPklZxva80061QiPg==",
      "dev": true,
      "requires": {
        "css-unit-converter": "^1.1.1",
        "postcss-value-parser": "^3.3.0"
      }
    },

**Comment by DeepakArora76** [comment]
@HakobiDev  I do not see any such errors at my end after downloading the package and testing it locally. I have created a demo repo for you to try it out.

[Nativescript DeviceInfo Demo JS](https://github.com/DeepakArora76/NativescriptDeviceInfoJSDemo.git)
